version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: ${CONTAINER_NAME}
    ports:
      - "${DB_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
